app/controllers.py
from flask import (Blueprint, render_template, request, redirect, url_for, session,
                   flash, jsonify, make_response, send_file)
from sqlalchemy import and_, cast, String, or_
from sqlalchemy.exc import SQLAlchemyError
from functools import wraps
from app.models import db, Doctor, Paciente, Cita, Tratamiento, FormularioMedico
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Message
from app import mail
from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import json
from decimal import Decimal
from datetime import date
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet ,ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from pytz import timezone

main_bp = Blueprint('main', __name__)
s = URLSafeTimedSerializer('clave_secreta')


# Decorador para rutas que requieren autenticación
def login_requerido(funcion):
    @wraps(funcion)
    def decorador(*args, **kwargs):
        if 'doctor_id' not in session:
            return redirect(url_for('main.iniciar_sesion'))
        return funcion(*args, **kwargs)
    return decorador

# Ruta de inicio
@main_bp.route('/')
def inicio():
    if 'doctor_id' not in session:
        flash('Por favor, inicia sesión para continuar.', 'info')
        
        return redirect(url_for('main.iniciar_sesion'))
    return redirect(url_for('main.iniciar_sesion'))

# Pantalla de inicio de sesión
@main_bp.route('/iniciar-sesion', methods=['GET', 'POST'])
def iniciar_sesion():
    if request.method == 'POST':
        email = request.form['email']
        contraseña = request.form['contraseña']
        doctor = Doctor.query.filter_by(email=email).first()

        if doctor and check_password_hash(doctor.contraseña, contraseña):
            session['doctor_id'] = doctor.doctor_id
            session['doctor_nombre'] = doctor.nombre
            return redirect(url_for('main.dashboard'))
        else:
            flash('Correo o contraseña incorrectos.', 'error')
    return render_template('autenticacion/iniciar_sesion.html')

# Ruta de registro
@main_bp.route('/registrarse', methods=['GET', 'POST'])
def registrarse():
    if request.method == 'POST':
        datos = {
            'ci': request.form['ci'],
            'nombre': request.form['nombre'],
            'paterno': request.form.get('paterno'),
            'materno': request.form.get('materno'),
            'especialidad': request.form.get('especialidad'),
            'telefono': request.form.get('telefono'),
            'paterno': request.form.get('paterno'),
            'fecha_nacimiento': request.form.get('fecha_nacimiento'),
            'email': request.form['email'],
            'contraseña': generate_password_hash(request.form['contraseña'])
        }

        if Doctor.query.filter_by(email=datos['email']).first():
            flash('El correo electrónico ya está registrado.', 'error')
            return redirect(url_for('main.registrarse'))

        try:
            nuevo_doctor = Doctor(**datos)
            db.session.add(nuevo_doctor)
            db.session.commit()
            flash('Registro exitoso. Ahora puedes iniciar sesión.', 'success')
            return redirect(url_for('main.iniciar_sesion'))
        except SQLAlchemyError as e:
            db.session.rollback()
            flash(f'Error al registrarse: {str(e)}', 'error')
    return render_template('autenticacion/registrarse.html')

# Ruta para cerrar sesión
@main_bp.route('/cerrar-sesion')
def cerrar_sesion():
    session.clear()
    return redirect(url_for('main.iniciar_sesion'))

# Dashboard principal
@main_bp.route('/dashboard')
@login_requerido
def dashboard():
    doctor_id = session['doctor_id']
    doctor = Doctor.query.get(doctor_id)
    pacientes = Paciente.query.filter_by(doctor_id=doctor_id).all()
    citas_pendientes = Cita.query.filter_by(doctor_id=doctor_id, estado='Pendiente').all()
    tratamientos_activos = Tratamiento.query.filter_by(paciente_id=doctor_id, estado='En Progreso').all()

    return render_template('dashboard.html', doctor=doctor, pacientes=pacientes, citas=citas_pendientes, tratamientos=tratamientos_activos)
# Gestión de doctor
@main_bp.route('/doctor/<int:doctor_id>', methods=['GET'])
@login_requerido
def detalle_doctor(doctor_id):
    doctor = Doctor.query.get_or_404(doctor_id)
    if doctor.doctor_id != session.get('doctor_id'):
        flash('No tienes permiso para ver este perfil.', 'error')
        return redirect(url_for('main.dashboard'))
    return render_template('doctor/detalle_doctor.html', doctor=doctor)


# Editar Doctor
@main_bp.route('/doctor/<int:doctor_id>/editar', methods=['GET', 'POST'])
@login_requerido
def editar_doctor(doctor_id):
    doctor = Doctor.query.get_or_404(doctor_id)
    if doctor.doctor_id != session.get('doctor_id'):
        flash('No tienes permiso para editar este perfil.', 'error')
        return redirect(url_for('main.dashboard'))
    
    if request.method == 'POST':
        # Actualización de datos
        doctor.nombre = request.form.get('nombre')
        doctor.paterno = request.form.get('paterno')
        doctor.materno = request.form.get('materno')
        doctor.ci = request.form.get('ci')
        doctor.fecha_nacimiento = request.form.get('fecha_nacimiento')
        doctor.especialidad = request.form.get('especialidad')
        doctor.telefono = request.form.get('telefono')
        doctor.email = request.form.get('email')
        
        # Manejo de contraseña opcional con encriptación
        nueva_contraseña = request.form.get('contraseña')
        if nueva_contraseña:
            doctor.contraseña = generate_password_hash(nueva_contraseña)
        
        try:
            db.session.commit()
            flash('Perfil actualizado exitosamente.', 'success')
            return redirect(url_for('main.detalle_doctor', doctor_id=doctor_id))
        except Exception as e:
            db.session.rollback()
            flash('Hubo un error al actualizar los datos. Inténtalo de nuevo.', 'error')
    
    return render_template('doctor/editar_doctor.html', doctor=doctor)




# Gestión de pacientes
#Listar Pacientes
@main_bp.route('/pacientes')
@login_requerido
def listar_pacientes():


    doctor_id = session.get('doctor_id')  # Usar `get` para evitar errores si no existe la clave
    if not doctor_id:
        # Manejo del caso en que `doctor_id` no está en la sesión
        return redirect('/login')  # O la página que corresponda
    
    # Obtener al doctor desde la base de datos
    doctor = Doctor.query.get(doctor_id)
    if not doctor:
        # Manejo del caso en que el doctor no existe
        return "Doctor no encontrado", 404

    # Obtener los pacientes asociados al doctor con paginación
    page = request.args.get('page', 1, type=int)
    pacientes_paginados = Paciente.query.filter_by(doctor_id=doctor_id).paginate(page=page, per_page=10)

    # Pasar el doctor y los pacientes paginados al template
    return render_template(
        'pacientes/listar_pacientes.html', 
        pacientes=pacientes_paginados.items, 
        doctor=doctor,
        pagination=pacientes_paginados
    )

#Buscar Paciente
@main_bp.route('/pacientes/buscar', methods=['GET', 'POST'])
@login_requerido
def buscar_pacientes():
    doctor_id = session.get('doctor_id')
    if not doctor_id:
        return redirect(url_for('main.iniciar_sesion'))

    query = Paciente.query.filter_by(doctor_id=doctor_id)
    
    if request.method == 'POST':
        ci = request.form.get('ci')

        if ci:
            # Usar cast para convertir `ci` a texto y luego usar ILIKE para la comparación
            query = query.filter(cast(Paciente.ci, String).ilike(f'%{ci}%'))

    page = request.args.get('page', 1, type=int)
    pacientes_paginados = query.paginate(page=page, per_page=3)

    return render_template(
        'pacientes/listar_pacientes.html', 
        pacientes=pacientes_paginados.items, 
        pagination=pacientes_paginados
    )



#Crear Paciente
@main_bp.route('/paciente/crear', methods=['GET', 'POST'])
@login_requerido
def crear_paciente():
    if request.method == 'POST':
        datos = {
            'nombre': request.form['nombre'],
            'paterno': request.form.get('paterno'),
            'materno': request.form.get('materno'),
            'ci': request.form.get('ci'),
            'fecha_nacimiento': request.form.get('fecha_nacimiento'),
            'direccion': request.form.get('direccion'),
            'paterno': request.form.get('paterno'),
            'telefono': request.form.get('telefono'),
            'celular': request.form.get('celular'),
            'estado_civil': request.form.get('estado_civil'),
            'ocupacion': request.form.get('ocupacion'),
            'doctor_id': session['doctor_id']
        }
        nuevo_paciente = Paciente(**datos)
        db.session.add(nuevo_paciente)
        db.session.commit()
        flash('Paciente creado exitosamente.', 'success')
        return redirect(url_for('main.listar_pacientes'))
    return render_template('pacientes/crear_paciente.html')

#Detalle del Paciente
@main_bp.route('/paciente/<int:paciente_id>')
@login_requerido
def detalle_paciente(paciente_id):
    paciente = Paciente.query.get_or_404(paciente_id)
    if paciente.doctor_id != session['doctor_id']:
        flash('No tienes permiso para ver este paciente.', 'error')
        return redirect(url_for('main.listar_pacientes'))

    page_tratamientos = request.args.get('page_tratamientos', 1, type=int)
    page_citas = request.args.get('page_citas', 1, type=int)

    tratamientos_activos_paginados = Tratamiento.query.filter_by(paciente_id=paciente_id, estado='En Progreso').paginate(page=page_tratamientos, per_page=5)

app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="DentAPP 1.1 - Gestión de pacientes y doctores.">
    <meta name="author" content="Tu nombre o equipo">
    <meta name="keywords" content="dentista, pacientes, doctores, gestión">
    <title>{% block title %}DentAPP 1.1{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <!-- Íconos de Bootstrap -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">

    <!-- CSS Personalizado -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='img/dental_tooth_icon_149293.ico') }}" type="image/x-icon">

    <style>
        :root {
            --primary-color: #68c3b7;
            --secondary-color: #539091;
            --highlight-color: #47d2ba;
            --background-light: #f8fafc;
            --gradient-color-1: rgba(104, 195, 183, 0.8);
            --gradient-color-2: rgba(83, 144, 145, 0.8);
            --background-image: url("static/img/fondo_dental7.jpg"); 
        }

        body {
            font-family: 'Poppins', sans-serif;
            color: var(--text-color);
            background: linear-gradient(135deg, var(--gradient-color-1), var(--gradient-color-2));
            background-attachment: fixed;
            background-size: cover;
            background-image: var(--background-image);
        }

        .navbar {
            background-color: var(--primary-color);
        }

        .footer {
            background-color: var(--secondary-color);
        }

        .btn-primary {
            background-color: var(--highlight-color);
            border-color: var(--highlight-color);
        }

        .btn-primary:hover {
            background-color: var(--primary-color);
            border-color: var(--primary-color);
        }

        .badge-warning {
            background-color: var(--highlight-color);
            color: #ffffff;
        }

        a {
            color: var(--highlight-color);
            text-decoration: none;
        }

        a:hover {
            color: var(--primary-color);
            text-decoration: underline;
        }

        .navbar-brand i {
            color: #ffffff;
        }

        /* Efecto difuminado adicional para contenedores principales */
        .container-fluid {
            background-color: var(--gradient-overlay);
            border-radius: 15px;
            padding: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .modo-oscuro {
            --primary-color: #1a1a1a;
            --secondary-color: #282828;
            --background-color: #121212;
            --text-color: #ffffff;
            /* Ajusta otros colores y estilos según sea necesario */
        }

        body.modo-oscuro {
            background-color: var(--background-color);
            color: var(--text-color);
        }

        /* Estilos Alerta */
        .custom-alert {
            font-family: Arial, sans-serif;
            font-size: 1rem;
            padding: 15px 20px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
        }
        .alert-success {
            background-color: #d4edda;
            color: #155724;
            border-color: #c3e6cb;
        }
        .alert-success i {
            color: #155724;
        }
        .alert-danger {
            background-color: #f8d7da;
            color: #721c24;
            border-color: #f5c6cb;
        }
        .alert-danger i {
            color: #721c24;
        }
        .alert-info {
            background-color: #d1ecf1;
            color: #0c5460;
            border-color: #bee5eb;
        }
        .alert-info i {
            color: #0c5460;
        }
        .alert-warning {
            background-color: #fff3cd;
            color: #856404;
            border-color: #ffeeba;
        }
        .alert-warning i {
            color: #856404;
        }
        </style>
    </head>

    <body>
        <!-- Barra de Navegación -->
        <nav class="navbar navbar-expand-lg navbar-dark shadow-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.dashboard') }}">
            <i class="bi bi-tooth" style="font-size: 1.5rem;"></i> <span style="font-size: 1.25rem;">DentAPP 1.1</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'main.dashboard' %}active{% endif %}" href="{{ url_for('main.dashboard') }}">
                    <i class="bi bi-house-door"></i> Inicio
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'main.listar_pacientes' %}active{% endif %}" href="{{ url_for('main.listar_pacientes') }}">
                    <i class="bi bi-person-lines-fill"></i> Pacientes
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'main.listar_citas' %}active{% endif %}" href="{{ url_for('main.listar_citas') }}">
                    <i class="bi bi-calendar-check"></i> Citas
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'main.generar_informe_doctor' %}active{% endif %}" href="{{ url_for('main.generar_informe_doctor', doctor_id=session.get('doctor_id')) }}">
                    <i class="bi bi-bar-chart"></i> Reportes
                </a>
                </li>
                
                {% if session.get('doctor_id') %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person-circle"></i> Mi Perfil
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li>
                        <a class="dropdown-item" href="{{ url_for('main.detalle_doctor', doctor_id=session.get('doctor_id')) }}">
                        Ver perfil
                        </a>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        <a class="dropdown-item text-danger" href="{{ url_for('main.cerrar_sesion') }}">
                        <i class="bi bi-box-arrow-right"></i> Cerrar sesión
                        </a>
                    </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
            </div>
        </div>
        </nav>
        
        <!-- Mensaje Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container mt-4">
            {% for category, message in messages %}
                <div id="flashMessage" class="alert alert-{{ category }} alert-dismissible fade show custom-alert" role="alert">
                {% if category == 'success' %}
                    <i class="bi bi-check-circle-fill"></i>
                {% elif category == 'danger' %}
                    <i class="bi bi-exclamation-triangle-fill"></i>
                {% elif category == 'info' %}
                    <i class="bi bi-info-circle-fill"></i>
                {% elif category == 'warning' %}
                    <i class="bi bi-exclamation-circle-fill"></i>
                {% endif %}
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %}

    <!-- Contenido Principal -->
    <div class="container-fluid">
        <div class="row">
            <main class="col-12 ms-sm-auto px-md-4 py-4">
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div> 


    <!-- Footer -->
    <footer class="footer py-3 text-white text-center shadow-sm">
        <div class="container">
            <span>&copy; 2025 DentAPP 1.1. Todos los derechos reservados.</span>
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <!-- Script de configuración -->
    <script src="{{ url_for('static', filename='js/config.js') }}"></script>
    
    <script>
        // Configuración para que los mensajes flash desaparezcan automáticamente
        setTimeout(() => {
            const flashMessages = document.querySelectorAll('.alert');
            flashMessages.forEach(flashMessage => {
                const alert = bootstrap.Alert.getOrCreateInstance(flashMessage); // Obtén la instancia de Bootstrap Alert
                alert.close(); // Cierra el mensaje
            });
        }, 5000); // 5000 ms = 5 segundos
    </script>
    
</body>

</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Inicio - Bienvenido {% endblock %}

{% block content %}
    <div class="container py-5">
        <!-- Encabezado Principal alineado a la derecha -->
        <div class="text-end mb-5" style="padding: 20px;">
            <!-- Cambié el tipo de letra de la frase -->
            <h1 class="display-4 fw-bold" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #ffffff;text-align: left;">
                "Tu sonrisa es nuestra pasión"
            </h1>
            <h1 class="display-4 fw-bold" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;color: #ffffff;text-align: left;">El cuidado dental comienza aquí, con dedicación y precisión.</h1>
            <h1 class="display-4 fw-bold" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;color: #ffffff;">Bienvenido, Doctor/a</h1>
            <!-- Cambié el tipo de letra del apellido -->
            <h1 class="display-5 fw-bold" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color:#ffffff;">{{ doctor.paterno }}</h1>
        </div>

        <!-- Espacio adicional para separación -->
        <div class="my-5"></div>

        <!-- Opciones del dashboard en contenedor transparente -->
        <div class="rounded-4" style="background-color: rgba(248, 249, 250, 0.1);">
            <div class="card-body py-5">
            <div class="row">
                <!-- Gestión de Pacientes -->
                <div class="col-md-4">
                <div class="card shadow-sm border-0 rounded-4" style="background-color: #d9f3f2;">
                    <div class="card-body text-center">
                    <i class="bi bi-person-lines-fill text-info display-1 mb-3"></i>
                    <h5 class="card-title text-dark">Gestión de Pacientes</h5>
                    <p class="card-text">Administra, edita y consulta la información de tus pacientes.</p>
                    <a href="{{ url_for('main.listar_pacientes') }}" class="btn btn-outline-info">Ir a Pacientes</a>
                    </div>
                </div>
                </div>

                <!-- Gestión de Citas -->
                <div class="col-md-4">
                <div class="card shadow-sm border-0 rounded-4" style="background-color: #e6f9f4;">
                    <div class="card-body text-center">
                    <i class="bi bi-calendar-check text-success display-1 mb-3"></i>
                    <h5 class="card-title text-dark">Gestión de Citas</h5>
                    <p class="card-text">Crea, edita y organiza las citas de tus pacientes.</p>
                    <a href="{{ url_for('main.listar_citas') }}" class="btn btn-outline-success">Ir a Citas</a>
                    </div>
                </div>
                </div>

                <!-- Reportes -->
                <div class="col-md-4">
                <div class="card shadow-sm border-0 rounded-4" style="background-color: #f9f3e6;">
                    <div class="card-body text-center">
                    <i class="bi bi-bar-chart text-warning display-1 mb-3"></i>
                    <h5 class="card-title text-dark">Reportes</h5>
                    <p class="card-text">Visualización y generación de reportes detallados</p>
                    <a href="{{ url_for('main.generar_informe_doctor', doctor_id=session.get('doctor_id')) }}" class="btn btn-outline-warning">Ir a Reportes</a>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Tu propio CSS (opcional) -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}"> 
</head>
<body class="bg-light">
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card p-4 shadow-lg" style="max-width: 400px; width: 100%;">
            <h1 class="text-center mb-4">Iniciar Sesión</h1>
            
            <form method="POST" action="{{ url_for('main.login') }}">
                <div class="mb-3">
                    <label for="email" class="form-label">Correo electrónico:</label>
                    <input type="email" id="email" name="email" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="contraseña" class="form-label">Contraseña:</label>
                    <input type="password" id="contraseña" name="contraseña" class="form-control" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">Iniciar Sesión</button>
            </form>
            <p class="text-center mt-3">
                ¿No tienes una cuenta? <a href="{{ url_for('main.register') }}">Regístrate aquí</a>
                ¿Olvidaste tu contraseña? <a href="{{ url_for('main.reset_password') }}">Restablecer contraseña</a>
            </p>
            
        </div>
    </div>

    <!-- Bootstrap Bundle JS -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Tu propio CSS (opcional) -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body class="bg-light">
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card p-4 shadow-lg" style="max-width: 500px; width: 100%;">
            <h1 class="text-center mb-4">Registro de Usuario</h1>
            
            <form action="{{ url_for('main.register') }}" method="POST">
                <div class="mb-3">
                    <label for="ci" class="form-label">CI:</label>
                    <input type="text" name="ci" id="ci" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre:</label>
                    <input type="text" name="nombre" id="nombre" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="paterno" class="form-label">Apellido Paterno:</label>
                    <input type="text" name="paterno" id="paterno" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="materno" class="form-label">Apellido Materno:</label>
                    <input type="text" name="materno" id="materno" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="especialidad" class="form-label">Especialidad:</label>
                    <input type="text" name="especialidad" id="especialidad" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="telefono" class="form-label">Teléfono:</label>
                    <input type="text" name="telefono" id="telefono" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="fecha_nacimiento" class="form-label">Fecha de Nacimiento:</label>
                    <input type="date" name="fecha_nacimiento" id="fecha_nacimiento" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Correo Electrónico:</label>
                    <input type="email" name="email" id="email" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="contraseña" class="form-label">Contraseña:</label>
                    <input type="password" name="contraseña" id="contraseña" class="form-control" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">Registrarse</button>
            </form>
        </div>
    </div>

    <!-- Bootstrap Bundle JS -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>